---
- name: Creates directory
  file:
    path: /tmp/hadoop-conf
    state: directory

- name: Fetch the file from the hadoop_server to ansible master
  run_once: yes
  fetch: src=/etc/hadoop/conf/{{ item }} dest=/tmp/hadoop-conf/ flat=yes
  with_items: 
    -  capacity-scheduler.xml  
    -  configuration.xsl
    -  container-executor.cfg
    -  core-site.xml
    -  hadoop-env.sh
    -  hadoop-metrics2.properties
    -  hadoop-metrics.properties
    -  hadoop-policy.xml
    -  hdfs-site.xml
    -  log4j.properties
    -  mapred-env.sh
    -  mapred-queues.xml.template
    -  mapred-site.xml
    -  mapred-site.xml.template
    -  slaves
    -  ssl-client.xml
    -  ssl-client.xml.example
    -  ssl-server.xml
    -  ssl-server.xml.example
    -  taskcontroller.cfg
    -  yarn-env.sh
    -  yarn-site.xml 
          
