---

- name: Airflow | Ensure Airflow group
  group:
    name: "{{ airflow_group }}"
    gid: 1004

- name: Airflow | Ensure Airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    shell: /bin/bash
    uid: 1003

- name: Airflow | Create path for Airflow home
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Create path for configuration files
  file:
    path: "{{ airflow_environment_file_folder }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Installing dependencies
  apt:
    pkg: "{{ airflow_required_libs }}"
    state: present
    update_cache: yes


- name: Airflow | Set AIRFLOW_HOME environment variable in /etc/environment
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME={{ airflow_home }}'

- name: Airflow | Installing Airflow
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: apache-airflow
    version: "{{ airflow_version }}"
    extra_args: --no-cache-dir
  register: airflow_install
  environment:
    SLUGIFY_USES_TEXT_UNIDECODE: "yes"



- name: Airflow | Copy Environment File
  template:
    src: airflow-environment-file.j2
    dest: "{{ airflow_environment_file_folder }}/airflow"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Copy Daemon scripts
  template:
    src: "{{ item.key }}.service.j2"
    dest: /etc/systemd/system/{{ item.key }}.service
    mode: 0644
  notify: restart {{ item.key }}
  with_dict: "{{ airflow_services }}"
  when: "{{ item.value.enabled }}"


